[workspace]

members = [
    "algorithms",
    "basic_concepts",
    "basic_types",
    "basic_funcs",
    "control_flows",

    "std_fs",
    
    "play-async"
]

exclude = [
    "play-actix",
    "learn-rust",
    "play-wgpu",
    "play-bevy"
]
