[workspace]

members = [
    "algorithms",
    "basic_concepts",
    "basic_types",
    "basic_funcs",
    "control_flows",
    "generic_types",

    "std_fs"
]

exclude = [
    "math3d",
    "play-actix",
    "learn-rust",
    "play-wgpu",
    "play-bevy"
]
