[workspace]

members = [
    "algorithms",
    "basic_concepts",
    "basic_types",
    "basic_funcs",
    
    "play-thread",
    "play-async",
    "play-pg",
    "play-bevy"
]

exclude = [
    "play-actix",
    "learn-rust",
    "play-wgpu"
]
